export const DEFAULT_ENDPOINT = 'https://api.blockloghq.com/api/v1';
export const DEFAULT_BATCH_SIZE = 100;
export const DEFAULT_FLUSH_INTERVAL = 1000; // 1s
export const DEFAULT_TIMEOUT = 10000; // 10s
export const DEFAULT_RETRY_COUNT = 3;
export const DEFAULT_SIGNING_ALG = 'ed25519';
export const DEFAULT_ENABLE_SIGNING = false;
export const DEFAULT_ENABLE_COMPRESSION = false;
export const DEFAULT_DEBUG = false;
