export const AGENT_START = 'AGENT_START';
export const AGENT_COMPLETE = 'AGENT_COMPLETE';
export const AGENT_ERROR = 'AGENT_ERROR';

export const TOOL_START = 'TOOL_START';
export const TOOL_COMPLETE = 'TOOL_COMPLETE';
export const TOOL_ERROR = 'TOOL_ERROR';
export const TOOL_CALL = 'TOOL_CALL';
export const TOOL_RESULT = 'TOOL_RESULT';

export const DECISION_START = 'DECISION_START';
export const DECISION_INPUT = 'DECISION_INPUT';
export const DECISION_OUTPUT = 'DECISION_OUTPUT';
export const DECISION_TAG = 'DECISION_TAG';
export const DECISION_COMPLETE = 'DECISION_COMPLETE';
export const DECISION_CREATED = 'DECISION_CREATED';
export const DECISION_APPROVED = 'DECISION_APPROVED';
